# Generated by Django 4.0.4 on 2022-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0002_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
